require 'capybara'
require 'capybara/rspec'
require 'rspec'
require 'rspec/expectations'
require 'rspec/matchers'
require 'selenium/webdriver'
require 'selenium/webdriver/common/wait'
require 'faker'

require 'steps/action/check_steps'
require 'steps/action/choose_steps'
require 'steps/action/click_steps'
require 'steps/action/fill_steps'
require 'steps/action/key_action_steps'
require 'steps/action/select_steps'
require 'steps/assertion/assertion_steps'
require 'steps/customized/customized_steps'
require 'steps/util/browser_util_steps'
require 'steps/util/browser_util_methods'
require 'steps/util/fill_in_util'
require 'steps/config'
require 'steps/global/global_context'
require 'steps/config'

