require 'capybara'
require 'capybara/cucumber'
require 'capybara/dsl'
require 'capybara/rspec'
require 'rspec'
require 'rspec/expectations'
require 'rspec/matchers'
require 'selenium-cucumber'
require 'selenium/webdriver'
require 'selenium/webdriver/common/wait'

require 'steps/assertion'
require 'steps/browser'
require 'steps/check'
require 'steps/click'
require 'steps/fill'
require 'steps/select'
require 'steps/unclassified'